[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "velastic"
version = "0.0.1.dev"
license = { text = "Apache-2.0" }
dependencies = [
]


[tool.setuptools]
packages = ["velastic"]

