# c.f. https://github.com/pre-commit/action?tab=readme-ov-file#using-this-action
name: pre-commit

# No need to avoid / cancel lightweight pre-commit jobs
on:
  pull_request:
  push:
    branches:
      - main

# Declare permissions just read content.
permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: .
      - uses: actions/setup-python@v3
      - name: Install ruff
        run: pip install -e ".[dev]"

      - name: Run ruff format and check
        run: |
          pwd && ls -la
          ruff check tasks tests veomni docs setup.py
          ruff format --check tasks tests veomni docs setup.py
